
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Sydney Chin
tagline: Business/Accounting Student
pic: senior pic 100.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: sydneychin47@gmail.com
phone: 714 398 5326
linkedin: sydneychin
github: sydneychin



# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
